name: Test CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      NPM_TOKEN: ${{ secrets.MY_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, and test
        run: |
          yarn
          yarn lint
          yarn test
      - uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: coverage/
      - name: publish packages
        run: |
          cat ./scripts/npm.sh | bash -
          yarn publish:packages
